import type { Metadata } from 'next';

import '@/scss/main.scss';
import Header from './components/header/header';
import Footer from './components/footer/footer';
import { RootStoreContext } from './root-store-context';
import RootStore from './store/root-store';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="body">
          <Header />
          <main className="body__main main">{children}</main>
          <Footer />
        {/* <RootStoreContext.Provider value={new RootStore()}>
        </RootStoreContext.Provider> */}
      </body>
    </html>
  );
}
